### ISSUE TITLE
1.0.0-beta.2 not found

### ISSUE THREAD

**Issue by Calvin-Huang** [sunshinejr/RxPermission#18]
Hi, I tried to install `1.0.0-beta.2` via Cocoapods but after I update repo source it still told me `1.0.0-beta.2` not exists.

The latest version shows `1.0.0-beta.1` in [cocoapods.org](https://cocoapods.org/?q=RxPermission).

If you forget to upload to cocoapods, I just writing to remind you of that, but if that is my pod's problem, please tell me and I will try to fix it.

**Comment by sunshinejr** [comment]
Hey @Calvin-Huang! I'm really sorry but when I was doing the beta.2 release I didn't check if Permission is already updated to Swift 3.0, and in fact it wasn't so I had to wait for the update there. That's why the beta.2 tag is uploaded but it is not on the CocoaPods. I'm gonna take a look at Permission later this week because right now I don't really have time to do it 😓

**Comment by Calvin-Huang** [comment]
@sunshinejr, Premission is already updated to Swift 3.0.
But it didn't mention that at CHANGELOG or other document 😆
I'm look forward to you update. (I wish I can help you but I don't have time either, sorry😭 ).
